package com.cus.jastip.transaction.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import javax.validation.constraints.*;

import org.springframework.data.elasticsearch.annotations.Document;
import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;

import com.cus.jastip.transaction.domain.enumeration.ActorType;

import com.cus.jastip.transaction.domain.enumeration.OfferingStatus;

/**
 * A Offering.
 */
@Entity
@Table(name = "offering")
@Document(indexName = "offering")
public class Offering extends AbstractAuditingEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(name = "actor_id", nullable = false)
    private Long actorId;

    @Enumerated(EnumType.STRING)
    @Column(name = "actor_type")
    private ActorType actorType;

    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    private OfferingStatus status;

    @NotNull
    @Column(name = "return_date", nullable = false)
    private Instant returnDate;

    @Column(name = "sent_date")
    private Instant sentDate;

    @NotNull
    @Column(name = "sent_from_country_id", nullable = false)
    private Long sentFromCountryId;

    @NotNull
    @Column(name = "sent_from_country_name", nullable = false)
    private String sentFromCountryName;

    @NotNull
    @Column(name = "sent_from_city_id", nullable = false)
    private Long sentFromCityId;

    @NotNull
    @Column(name = "sent_from_city_name", nullable = false)
    private String sentFromCityName;

    @Column(name = "offering_date")
    private Instant offeringDate;

    /**
     * generated by system
     */
    @NotNull
    @ApiModelProperty(value = "generated by system", required = true)
    @Column(name = "timezone", nullable = false)
    private String timezone;

    @Column(name = "offering_expired_date")
    private Instant offeringExpiredDate;

    @Min(value = 1)
    @Column(name = "quantity")
    private Integer quantity;

    @DecimalMin(value = "0")
    @Column(name = "price_item")
    private Double priceItem;

    @DecimalMin(value = "0")
    @Column(name = "service_fee")
    private Double serviceFee;

    @DecimalMin(value = "0")
    @Column(name = "jastip_fee")
    private Double jastipFee;

    @DecimalMin(value = "0")
    @Column(name = "total_fee")
    private Double totalFee;

    @Column(name = "trip_id")
    private Long tripId;

    @Column(name = "trip_city_name")
    private String tripCityName;

    @Column(name = "trip_country_name")
    private String tripCountryName;

    @Column(name = "trip_start_date")
    private Instant tripStartDate;

    @Column(name = "trip_end_date")
    private Instant tripEndDate;

    @Column(name = "actor_city_from_name")
    private String actorCityFromName;

    @Column(name = "shopping_date")
    private Instant shoppingDate;

    @Column(name = "delivery_date")
    private Instant deliveryDate;

    @Column(name = "notes")
    private String notes;

    @ManyToOne
    private Posting posting;

    @OneToOne(mappedBy = "offering")
    @JsonIgnore
    private OfferingDeliveryInfo offeringDeliveryInfo;

    @OneToOne(mappedBy = "offering")
    @JsonIgnore
    private OfferingDeliveryService offeringDeliveryService;

    @OneToOne(mappedBy = "offering")
    @JsonIgnore
    private OfferingPayment offeringPayment;

    @OneToOne(mappedBy = "offering")
    @JsonIgnore
    private OfferingPuchase offeringPurchase;

    @OneToOne(mappedBy = "offering")
    @JsonIgnore
    private OfferingCourier offeringCourier;

    // jhipster-needle-entity-add-field - JHipster will add fields here, do not remove
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getActorId() {
        return actorId;
    }

    public Offering actorId(Long actorId) {
        this.actorId = actorId;
        return this;
    }

    public void setActorId(Long actorId) {
        this.actorId = actorId;
    }

    public ActorType getActorType() {
        return actorType;
    }

    public Offering actorType(ActorType actorType) {
        this.actorType = actorType;
        return this;
    }

    public void setActorType(ActorType actorType) {
        this.actorType = actorType;
    }

    public OfferingStatus getStatus() {
        return status;
    }

    public Offering status(OfferingStatus status) {
        this.status = status;
        return this;
    }

    public void setStatus(OfferingStatus status) {
        this.status = status;
    }

    public Instant getReturnDate() {
        return returnDate;
    }

    public Offering returnDate(Instant returnDate) {
        this.returnDate = returnDate;
        return this;
    }

    public void setReturnDate(Instant returnDate) {
        this.returnDate = returnDate;
    }

    public Instant getSentDate() {
        return sentDate;
    }

    public Offering sentDate(Instant sentDate) {
        this.sentDate = sentDate;
        return this;
    }

    public void setSentDate(Instant sentDate) {
        this.sentDate = sentDate;
    }

    public Long getSentFromCountryId() {
        return sentFromCountryId;
    }

    public Offering sentFromCountryId(Long sentFromCountryId) {
        this.sentFromCountryId = sentFromCountryId;
        return this;
    }

    public void setSentFromCountryId(Long sentFromCountryId) {
        this.sentFromCountryId = sentFromCountryId;
    }

    public String getSentFromCountryName() {
        return sentFromCountryName;
    }

    public Offering sentFromCountryName(String sentFromCountryName) {
        this.sentFromCountryName = sentFromCountryName;
        return this;
    }

    public void setSentFromCountryName(String sentFromCountryName) {
        this.sentFromCountryName = sentFromCountryName;
    }

    public Long getSentFromCityId() {
        return sentFromCityId;
    }

    public Offering sentFromCityId(Long sentFromCityId) {
        this.sentFromCityId = sentFromCityId;
        return this;
    }

    public void setSentFromCityId(Long sentFromCityId) {
        this.sentFromCityId = sentFromCityId;
    }

    public String getSentFromCityName() {
        return sentFromCityName;
    }

    public Offering sentFromCityName(String sentFromCityName) {
        this.sentFromCityName = sentFromCityName;
        return this;
    }

    public void setSentFromCityName(String sentFromCityName) {
        this.sentFromCityName = sentFromCityName;
    }

    public Instant getOfferingDate() {
        return offeringDate;
    }

    public Offering offeringDate(Instant offeringDate) {
        this.offeringDate = offeringDate;
        return this;
    }

    public void setOfferingDate(Instant offeringDate) {
        this.offeringDate = offeringDate;
    }

    public String getTimezone() {
        return timezone;
    }

    public Offering timezone(String timezone) {
        this.timezone = timezone;
        return this;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public Instant getOfferingExpiredDate() {
        return offeringExpiredDate;
    }

    public Offering offeringExpiredDate(Instant offeringExpiredDate) {
        this.offeringExpiredDate = offeringExpiredDate;
        return this;
    }

    public void setOfferingExpiredDate(Instant offeringExpiredDate) {
        this.offeringExpiredDate = offeringExpiredDate;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public Offering quantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Double getPriceItem() {
        return priceItem;
    }

    public Offering priceItem(Double priceItem) {
        this.priceItem = priceItem;
        return this;
    }

    public void setPriceItem(Double priceItem) {
        this.priceItem = priceItem;
    }

    public Double getServiceFee() {
        return serviceFee;
    }

    public Offering serviceFee(Double serviceFee) {
        this.serviceFee = serviceFee;
        return this;
    }

    public void setServiceFee(Double serviceFee) {
        this.serviceFee = serviceFee;
    }

    public Double getJastipFee() {
        return jastipFee;
    }

    public Offering jastipFee(Double jastipFee) {
        this.jastipFee = jastipFee;
        return this;
    }

    public void setJastipFee(Double jastipFee) {
        this.jastipFee = jastipFee;
    }

    public Double getTotalFee() {
        return totalFee;
    }

    public Offering totalFee(Double totalFee) {
        this.totalFee = totalFee;
        return this;
    }

    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    public Long getTripId() {
        return tripId;
    }

    public Offering tripId(Long tripId) {
        this.tripId = tripId;
        return this;
    }

    public void setTripId(Long tripId) {
        this.tripId = tripId;
    }

    public String getTripCityName() {
        return tripCityName;
    }

    public Offering tripCityName(String tripCityName) {
        this.tripCityName = tripCityName;
        return this;
    }

    public void setTripCityName(String tripCityName) {
        this.tripCityName = tripCityName;
    }

    public String getTripCountryName() {
        return tripCountryName;
    }

    public Offering tripCountryName(String tripCountryName) {
        this.tripCountryName = tripCountryName;
        return this;
    }

    public void setTripCountryName(String tripCountryName) {
        this.tripCountryName = tripCountryName;
    }

    public Instant getTripStartDate() {
        return tripStartDate;
    }

    public Offering tripStartDate(Instant tripStartDate) {
        this.tripStartDate = tripStartDate;
        return this;
    }

    public void setTripStartDate(Instant tripStartDate) {
        this.tripStartDate = tripStartDate;
    }

    public Instant getTripEndDate() {
        return tripEndDate;
    }

    public Offering tripEndDate(Instant tripEndDate) {
        this.tripEndDate = tripEndDate;
        return this;
    }

    public void setTripEndDate(Instant tripEndDate) {
        this.tripEndDate = tripEndDate;
    }

    public String getActorCityFromName() {
        return actorCityFromName;
    }

    public Offering actorCityFromName(String actorCityFromName) {
        this.actorCityFromName = actorCityFromName;
        return this;
    }

    public void setActorCityFromName(String actorCityFromName) {
        this.actorCityFromName = actorCityFromName;
    }

    public Instant getShoppingDate() {
        return shoppingDate;
    }

    public Offering shoppingDate(Instant shoppingDate) {
        this.shoppingDate = shoppingDate;
        return this;
    }

    public void setShoppingDate(Instant shoppingDate) {
        this.shoppingDate = shoppingDate;
    }

    public Instant getDeliveryDate() {
        return deliveryDate;
    }

    public Offering deliveryDate(Instant deliveryDate) {
        this.deliveryDate = deliveryDate;
        return this;
    }

    public void setDeliveryDate(Instant deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public String getNotes() {
        return notes;
    }

    public Offering notes(String notes) {
        this.notes = notes;
        return this;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Posting getPosting() {
        return posting;
    }

    public Offering posting(Posting posting) {
        this.posting = posting;
        return this;
    }

    public void setPosting(Posting posting) {
        this.posting = posting;
    }

    public OfferingDeliveryInfo getOfferingDeliveryInfo() {
        return offeringDeliveryInfo;
    }

    public Offering offeringDeliveryInfo(OfferingDeliveryInfo offeringDeliveryInfo) {
        this.offeringDeliveryInfo = offeringDeliveryInfo;
        return this;
    }

    public void setOfferingDeliveryInfo(OfferingDeliveryInfo offeringDeliveryInfo) {
        this.offeringDeliveryInfo = offeringDeliveryInfo;
    }

    public OfferingDeliveryService getOfferingDeliveryService() {
        return offeringDeliveryService;
    }

    public Offering offeringDeliveryService(OfferingDeliveryService offeringDeliveryService) {
        this.offeringDeliveryService = offeringDeliveryService;
        return this;
    }

    public void setOfferingDeliveryService(OfferingDeliveryService offeringDeliveryService) {
        this.offeringDeliveryService = offeringDeliveryService;
    }

    public OfferingPayment getOfferingPayment() {
        return offeringPayment;
    }

    public Offering offeringPayment(OfferingPayment offeringPayment) {
        this.offeringPayment = offeringPayment;
        return this;
    }

    public void setOfferingPayment(OfferingPayment offeringPayment) {
        this.offeringPayment = offeringPayment;
    }

    public OfferingPuchase getOfferingPurchase() {
        return offeringPurchase;
    }

    public Offering offeringPurchase(OfferingPuchase offeringPuchase) {
        this.offeringPurchase = offeringPuchase;
        return this;
    }

    public void setOfferingPurchase(OfferingPuchase offeringPuchase) {
        this.offeringPurchase = offeringPuchase;
    }

    public OfferingCourier getOfferingCourier() {
        return offeringCourier;
    }

    public Offering offeringCourier(OfferingCourier offeringCourier) {
        this.offeringCourier = offeringCourier;
        return this;
    }

    public void setOfferingCourier(OfferingCourier offeringCourier) {
        this.offeringCourier = offeringCourier;
    }
    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here, do not remove

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Offering offering = (Offering) o;
        if (offering.getId() == null || getId() == null) {
            return false;
        }
        return Objects.equals(getId(), offering.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getId());
    }

    @Override
    public String toString() {
        return "Offering{" +
            "id=" + getId() +
            ", actorId=" + getActorId() +
            ", actorType='" + getActorType() + "'" +
            ", status='" + getStatus() + "'" +
            ", returnDate='" + getReturnDate() + "'" +
            ", sentDate='" + getSentDate() + "'" +
            ", sentFromCountryId=" + getSentFromCountryId() +
            ", sentFromCountryName='" + getSentFromCountryName() + "'" +
            ", sentFromCityId=" + getSentFromCityId() +
            ", sentFromCityName='" + getSentFromCityName() + "'" +
            ", offeringDate='" + getOfferingDate() + "'" +
            ", timezone='" + getTimezone() + "'" +
            ", offeringExpiredDate='" + getOfferingExpiredDate() + "'" +
            ", quantity=" + getQuantity() +
            ", priceItem=" + getPriceItem() +
            ", serviceFee=" + getServiceFee() +
            ", jastipFee=" + getJastipFee() +
            ", totalFee=" + getTotalFee() +
            ", tripId=" + getTripId() +
            ", tripCityName='" + getTripCityName() + "'" +
            ", tripCountryName='" + getTripCountryName() + "'" +
            ", tripStartDate='" + getTripStartDate() + "'" +
            ", tripEndDate='" + getTripEndDate() + "'" +
            ", actorCityFromName='" + getActorCityFromName() + "'" +
            ", shoppingDate='" + getShoppingDate() + "'" +
            ", deliveryDate='" + getDeliveryDate() + "'" +
            ", notes='" + getNotes() + "'" +
            "}";
    }
}
