package com.cus.jastip.transaction.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import javax.validation.constraints.*;

import org.springframework.data.elasticsearch.annotations.Document;
import java.io.Serializable;
import java.time.Instant;
import java.util.HashSet;
import java.util.Set;
import java.util.Objects;

import com.cus.jastip.transaction.domain.enumeration.PostingType;

import com.cus.jastip.transaction.domain.enumeration.PostingStatus;

/**
 * A Posting.
 */
@Entity
@Table(name = "posting")
@Document(indexName = "posting")
public class Posting extends AbstractAuditingEntity  implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(name = "jhi_type")
    private PostingType type;

    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    private PostingStatus status;

    @NotNull
    @Column(name = "owner_id", nullable = false)
    private Long ownerId;

    @Column(name = "posting_date")
    private Instant postingDate;

    /**
     * generated by system
     */
    @NotNull
    @ApiModelProperty(value = "generated by system", required = true)
    @Column(name = "timezone", nullable = false)
    private String timezone;

    @NotNull
    @Column(name = "expired_date", nullable = false)
    private Instant expiredDate;

    @NotNull
    @Column(name = "product_name", nullable = false)
    private String productName;

    @Column(name = "brand")
    private String brand;

    @Lob
    @Column(name = "posting_item_img")
    private byte[] postingItemImg;

    @Column(name = "posting_item_img_content_type")
    private String postingItemImgContentType;

    @Column(name = "posting_item_img_url")
    private String postingItemImgUrl;

    @Column(name = "posting_item_img_thumb_url")
    private String postingItemImgThumbUrl;

    @NotNull
    @Column(name = "description", nullable = false)
    private String description;

    @NotNull
    @Min(value = 1)
    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    @Min(value = 0)
    @Column(name = "avaiable_quantity")
    private Integer avaiableQuantity;

    @Column(name = "reference_link")
    private String referenceLink;

    @NotNull
    @Column(name = "item_category_id", nullable = false)
    private Long itemCategoryId;

    @NotNull
    @Column(name = "item_category_name", nullable = false)
    private String itemCategoryName;

    @NotNull
    @Column(name = "item_sub_category_id", nullable = false)
    private Long itemSubCategoryId;

    @NotNull
    @Column(name = "item_sub_category_name", nullable = false)
    private String itemSubCategoryName;

    @Column(name = "additional_info")
    private String additionalInfo;

    @Column(name = "reference_place")
    private String referencePlace;

    @NotNull
    @Column(name = "country_buy_from_id", nullable = false)
    private Long countryBuyFromId;

    @NotNull
    @Column(name = "country_buy_from_name", nullable = false)
    private String countryBuyFromName;

    @Column(name = "city_buy_from_id")
    private Long cityBuyFromId;

    @Column(name = "city_buy_from_name")
    private String cityBuyFromName;

    @NotNull
    @Column(name = "country_sent_to_id", nullable = false)
    private Long countrySentToId;

    @NotNull
    @Column(name = "country_sent_to_name", nullable = false)
    private String countrySentToName;

    @Column(name = "city_sent_to_id")
    private Long citySentToId;

    @Column(name = "city_sent_to_name")
    private String citySentToName;

    @Column(name = "fragile")
    private Boolean fragile;

    @Column(name = "need_cooler")
    private Boolean needCooler;

    @Column(name = "other_note")
    private Boolean otherNote;

    @Column(name = "other_note_info")
    private String otherNoteInfo;

    /**
     * required of otherNote is true
     */
    @Min(value = 0)
    @ApiModelProperty(value = "required of otherNote is true")
    @Column(name = "item_weight")
    private Integer itemWeight;

    @Column(name = "package_size_id")
    private Long packageSizeId;

    @Column(name = "package_size_name")
    private String packageSizeName;

    @Column(name = "need_receipt")
    private Boolean needReceipt;

    @NotNull
    @DecimalMin(value = "0")
    @Column(name = "price_item", nullable = false)
    private Double priceItem;

    @NotNull
    @DecimalMin(value = "0")
    @Column(name = "service_fee", nullable = false)
    private Double serviceFee;

    @NotNull
    @DecimalMin(value = "0")
    @Column(name = "jastip_fee", nullable = false)
    private Double jastipFee;

    @NotNull
    @DecimalMin(value = "0")
    @Column(name = "total_fee", nullable = false)
    private Double totalFee;

    @Column(name = "accepted_offering_id")
    private Long acceptedOfferingId;

    @Column(name = "shopping_date")
    private Instant shoppingDate;

    @Column(name = "delivery_date")
    private Instant deliveryDate;

    @ManyToOne
    private Trip trip;

    @OneToMany(mappedBy = "posting")
    @JsonIgnore
    private Set<Offering> offerings = new HashSet<>();

    @OneToMany(mappedBy = "posting")
    @JsonIgnore
    private Set<Comment> comments = new HashSet<>();

    // jhipster-needle-entity-add-field - JHipster will add fields here, do not remove
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public PostingType getType() {
        return type;
    }

    public Posting type(PostingType type) {
        this.type = type;
        return this;
    }

    public void setType(PostingType type) {
        this.type = type;
    }

    public PostingStatus getStatus() {
        return status;
    }

    public Posting status(PostingStatus status) {
        this.status = status;
        return this;
    }

    public void setStatus(PostingStatus status) {
        this.status = status;
    }

    public Long getOwnerId() {
        return ownerId;
    }

    public Posting ownerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }

    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    public Instant getPostingDate() {
        return postingDate;
    }

    public Posting postingDate(Instant postingDate) {
        this.postingDate = postingDate;
        return this;
    }

    public void setPostingDate(Instant postingDate) {
        this.postingDate = postingDate;
    }

    public String getTimezone() {
        return timezone;
    }

    public Posting timezone(String timezone) {
        this.timezone = timezone;
        return this;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public Instant getExpiredDate() {
        return expiredDate;
    }

    public Posting expiredDate(Instant expiredDate) {
        this.expiredDate = expiredDate;
        return this;
    }

    public void setExpiredDate(Instant expiredDate) {
        this.expiredDate = expiredDate;
    }

    public String getProductName() {
        return productName;
    }

    public Posting productName(String productName) {
        this.productName = productName;
        return this;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getBrand() {
        return brand;
    }

    public Posting brand(String brand) {
        this.brand = brand;
        return this;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public byte[] getPostingItemImg() {
        return postingItemImg;
    }

    public Posting postingItemImg(byte[] postingItemImg) {
        this.postingItemImg = postingItemImg;
        return this;
    }

    public void setPostingItemImg(byte[] postingItemImg) {
        this.postingItemImg = postingItemImg;
    }

    public String getPostingItemImgContentType() {
        return postingItemImgContentType;
    }

    public Posting postingItemImgContentType(String postingItemImgContentType) {
        this.postingItemImgContentType = postingItemImgContentType;
        return this;
    }

    public void setPostingItemImgContentType(String postingItemImgContentType) {
        this.postingItemImgContentType = postingItemImgContentType;
    }

    public String getPostingItemImgUrl() {
        return postingItemImgUrl;
    }

    public Posting postingItemImgUrl(String postingItemImgUrl) {
        this.postingItemImgUrl = postingItemImgUrl;
        return this;
    }

    public void setPostingItemImgUrl(String postingItemImgUrl) {
        this.postingItemImgUrl = postingItemImgUrl;
    }

    public String getPostingItemImgThumbUrl() {
        return postingItemImgThumbUrl;
    }

    public Posting postingItemImgThumbUrl(String postingItemImgThumbUrl) {
        this.postingItemImgThumbUrl = postingItemImgThumbUrl;
        return this;
    }

    public void setPostingItemImgThumbUrl(String postingItemImgThumbUrl) {
        this.postingItemImgThumbUrl = postingItemImgThumbUrl;
    }

    public String getDescription() {
        return description;
    }

    public Posting description(String description) {
        this.description = description;
        return this;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public Posting quantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getAvaiableQuantity() {
        return avaiableQuantity;
    }

    public Posting avaiableQuantity(Integer avaiableQuantity) {
        this.avaiableQuantity = avaiableQuantity;
        return this;
    }

    public void setAvaiableQuantity(Integer avaiableQuantity) {
        this.avaiableQuantity = avaiableQuantity;
    }

    public String getReferenceLink() {
        return referenceLink;
    }

    public Posting referenceLink(String referenceLink) {
        this.referenceLink = referenceLink;
        return this;
    }

    public void setReferenceLink(String referenceLink) {
        this.referenceLink = referenceLink;
    }

    public Long getItemCategoryId() {
        return itemCategoryId;
    }

    public Posting itemCategoryId(Long itemCategoryId) {
        this.itemCategoryId = itemCategoryId;
        return this;
    }

    public void setItemCategoryId(Long itemCategoryId) {
        this.itemCategoryId = itemCategoryId;
    }

    public String getItemCategoryName() {
        return itemCategoryName;
    }

    public Posting itemCategoryName(String itemCategoryName) {
        this.itemCategoryName = itemCategoryName;
        return this;
    }

    public void setItemCategoryName(String itemCategoryName) {
        this.itemCategoryName = itemCategoryName;
    }

    public Long getItemSubCategoryId() {
        return itemSubCategoryId;
    }

    public Posting itemSubCategoryId(Long itemSubCategoryId) {
        this.itemSubCategoryId = itemSubCategoryId;
        return this;
    }

    public void setItemSubCategoryId(Long itemSubCategoryId) {
        this.itemSubCategoryId = itemSubCategoryId;
    }

    public String getItemSubCategoryName() {
        return itemSubCategoryName;
    }

    public Posting itemSubCategoryName(String itemSubCategoryName) {
        this.itemSubCategoryName = itemSubCategoryName;
        return this;
    }

    public void setItemSubCategoryName(String itemSubCategoryName) {
        this.itemSubCategoryName = itemSubCategoryName;
    }

    public String getAdditionalInfo() {
        return additionalInfo;
    }

    public Posting additionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
        return this;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    public String getReferencePlace() {
        return referencePlace;
    }

    public Posting referencePlace(String referencePlace) {
        this.referencePlace = referencePlace;
        return this;
    }

    public void setReferencePlace(String referencePlace) {
        this.referencePlace = referencePlace;
    }

    public Long getCountryBuyFromId() {
        return countryBuyFromId;
    }

    public Posting countryBuyFromId(Long countryBuyFromId) {
        this.countryBuyFromId = countryBuyFromId;
        return this;
    }

    public void setCountryBuyFromId(Long countryBuyFromId) {
        this.countryBuyFromId = countryBuyFromId;
    }

    public String getCountryBuyFromName() {
        return countryBuyFromName;
    }

    public Posting countryBuyFromName(String countryBuyFromName) {
        this.countryBuyFromName = countryBuyFromName;
        return this;
    }

    public void setCountryBuyFromName(String countryBuyFromName) {
        this.countryBuyFromName = countryBuyFromName;
    }

    public Long getCityBuyFromId() {
        return cityBuyFromId;
    }

    public Posting cityBuyFromId(Long cityBuyFromId) {
        this.cityBuyFromId = cityBuyFromId;
        return this;
    }

    public void setCityBuyFromId(Long cityBuyFromId) {
        this.cityBuyFromId = cityBuyFromId;
    }

    public String getCityBuyFromName() {
        return cityBuyFromName;
    }

    public Posting cityBuyFromName(String cityBuyFromName) {
        this.cityBuyFromName = cityBuyFromName;
        return this;
    }

    public void setCityBuyFromName(String cityBuyFromName) {
        this.cityBuyFromName = cityBuyFromName;
    }

    public Long getCountrySentToId() {
        return countrySentToId;
    }

    public Posting countrySentToId(Long countrySentToId) {
        this.countrySentToId = countrySentToId;
        return this;
    }

    public void setCountrySentToId(Long countrySentToId) {
        this.countrySentToId = countrySentToId;
    }

    public String getCountrySentToName() {
        return countrySentToName;
    }

    public Posting countrySentToName(String countrySentToName) {
        this.countrySentToName = countrySentToName;
        return this;
    }

    public void setCountrySentToName(String countrySentToName) {
        this.countrySentToName = countrySentToName;
    }

    public Long getCitySentToId() {
        return citySentToId;
    }

    public Posting citySentToId(Long citySentToId) {
        this.citySentToId = citySentToId;
        return this;
    }

    public void setCitySentToId(Long citySentToId) {
        this.citySentToId = citySentToId;
    }

    public String getCitySentToName() {
        return citySentToName;
    }

    public Posting citySentToName(String citySentToName) {
        this.citySentToName = citySentToName;
        return this;
    }

    public void setCitySentToName(String citySentToName) {
        this.citySentToName = citySentToName;
    }

    public Boolean isFragile() {
        return fragile;
    }

    public Posting fragile(Boolean fragile) {
        this.fragile = fragile;
        return this;
    }

    public void setFragile(Boolean fragile) {
        this.fragile = fragile;
    }

    public Boolean isNeedCooler() {
        return needCooler;
    }

    public Posting needCooler(Boolean needCooler) {
        this.needCooler = needCooler;
        return this;
    }

    public void setNeedCooler(Boolean needCooler) {
        this.needCooler = needCooler;
    }

    public Boolean isOtherNote() {
        return otherNote;
    }

    public Posting otherNote(Boolean otherNote) {
        this.otherNote = otherNote;
        return this;
    }

    public void setOtherNote(Boolean otherNote) {
        this.otherNote = otherNote;
    }

    public String getOtherNoteInfo() {
        return otherNoteInfo;
    }

    public Posting otherNoteInfo(String otherNoteInfo) {
        this.otherNoteInfo = otherNoteInfo;
        return this;
    }

    public void setOtherNoteInfo(String otherNoteInfo) {
        this.otherNoteInfo = otherNoteInfo;
    }

    public Integer getItemWeight() {
        return itemWeight;
    }

    public Posting itemWeight(Integer itemWeight) {
        this.itemWeight = itemWeight;
        return this;
    }

    public void setItemWeight(Integer itemWeight) {
        this.itemWeight = itemWeight;
    }

    public Long getPackageSizeId() {
        return packageSizeId;
    }

    public Posting packageSizeId(Long packageSizeId) {
        this.packageSizeId = packageSizeId;
        return this;
    }

    public void setPackageSizeId(Long packageSizeId) {
        this.packageSizeId = packageSizeId;
    }

    public String getPackageSizeName() {
        return packageSizeName;
    }

    public Posting packageSizeName(String packageSizeName) {
        this.packageSizeName = packageSizeName;
        return this;
    }

    public void setPackageSizeName(String packageSizeName) {
        this.packageSizeName = packageSizeName;
    }

    public Boolean isNeedReceipt() {
        return needReceipt;
    }

    public Posting needReceipt(Boolean needReceipt) {
        this.needReceipt = needReceipt;
        return this;
    }

    public void setNeedReceipt(Boolean needReceipt) {
        this.needReceipt = needReceipt;
    }

    public Double getPriceItem() {
        return priceItem;
    }

    public Posting priceItem(Double priceItem) {
        this.priceItem = priceItem;
        return this;
    }

    public void setPriceItem(Double priceItem) {
        this.priceItem = priceItem;
    }

    public Double getServiceFee() {
        return serviceFee;
    }

    public Posting serviceFee(Double serviceFee) {
        this.serviceFee = serviceFee;
        return this;
    }

    public void setServiceFee(Double serviceFee) {
        this.serviceFee = serviceFee;
    }

    public Double getJastipFee() {
        return jastipFee;
    }

    public Posting jastipFee(Double jastipFee) {
        this.jastipFee = jastipFee;
        return this;
    }

    public void setJastipFee(Double jastipFee) {
        this.jastipFee = jastipFee;
    }

    public Double getTotalFee() {
        return totalFee;
    }

    public Posting totalFee(Double totalFee) {
        this.totalFee = totalFee;
        return this;
    }

    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    public Long getAcceptedOfferingId() {
        return acceptedOfferingId;
    }

    public Posting acceptedOfferingId(Long acceptedOfferingId) {
        this.acceptedOfferingId = acceptedOfferingId;
        return this;
    }

    public void setAcceptedOfferingId(Long acceptedOfferingId) {
        this.acceptedOfferingId = acceptedOfferingId;
    }

    public Instant getShoppingDate() {
        return shoppingDate;
    }

    public Posting shoppingDate(Instant shoppingDate) {
        this.shoppingDate = shoppingDate;
        return this;
    }

    public void setShoppingDate(Instant shoppingDate) {
        this.shoppingDate = shoppingDate;
    }

    public Instant getDeliveryDate() {
        return deliveryDate;
    }

    public Posting deliveryDate(Instant deliveryDate) {
        this.deliveryDate = deliveryDate;
        return this;
    }

    public void setDeliveryDate(Instant deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public Trip getTrip() {
        return trip;
    }

    public Posting trip(Trip trip) {
        this.trip = trip;
        return this;
    }

    public void setTrip(Trip trip) {
        this.trip = trip;
    }

    public Set<Offering> getOfferings() {
        return offerings;
    }

    public Posting offerings(Set<Offering> offerings) {
        this.offerings = offerings;
        return this;
    }

    public Posting addOffering(Offering offering) {
        this.offerings.add(offering);
        offering.setPosting(this);
        return this;
    }

    public Posting removeOffering(Offering offering) {
        this.offerings.remove(offering);
        offering.setPosting(null);
        return this;
    }

    public void setOfferings(Set<Offering> offerings) {
        this.offerings = offerings;
    }

    public Set<Comment> getComments() {
        return comments;
    }

    public Posting comments(Set<Comment> comments) {
        this.comments = comments;
        return this;
    }

    public Posting addComment(Comment comment) {
        this.comments.add(comment);
        comment.setPosting(this);
        return this;
    }

    public Posting removeComment(Comment comment) {
        this.comments.remove(comment);
        comment.setPosting(null);
        return this;
    }

    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here, do not remove

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Posting posting = (Posting) o;
        if (posting.getId() == null || getId() == null) {
            return false;
        }
        return Objects.equals(getId(), posting.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getId());
    }

    @Override
    public String toString() {
        return "Posting{" +
            "id=" + getId() +
            ", type='" + getType() + "'" +
            ", status='" + getStatus() + "'" +
            ", ownerId=" + getOwnerId() +
            ", postingDate='" + getPostingDate() + "'" +
            ", timezone='" + getTimezone() + "'" +
            ", expiredDate='" + getExpiredDate() + "'" +
            ", productName='" + getProductName() + "'" +
            ", brand='" + getBrand() + "'" +
            ", postingItemImg='" + getPostingItemImg() + "'" +
            ", postingItemImgContentType='" + getPostingItemImgContentType() + "'" +
            ", postingItemImgUrl='" + getPostingItemImgUrl() + "'" +
            ", postingItemImgThumbUrl='" + getPostingItemImgThumbUrl() + "'" +
            ", description='" + getDescription() + "'" +
            ", quantity=" + getQuantity() +
            ", avaiableQuantity=" + getAvaiableQuantity() +
            ", referenceLink='" + getReferenceLink() + "'" +
            ", itemCategoryId=" + getItemCategoryId() +
            ", itemCategoryName='" + getItemCategoryName() + "'" +
            ", itemSubCategoryId=" + getItemSubCategoryId() +
            ", itemSubCategoryName='" + getItemSubCategoryName() + "'" +
            ", additionalInfo='" + getAdditionalInfo() + "'" +
            ", referencePlace='" + getReferencePlace() + "'" +
            ", countryBuyFromId=" + getCountryBuyFromId() +
            ", countryBuyFromName='" + getCountryBuyFromName() + "'" +
            ", cityBuyFromId=" + getCityBuyFromId() +
            ", cityBuyFromName='" + getCityBuyFromName() + "'" +
            ", countrySentToId=" + getCountrySentToId() +
            ", countrySentToName='" + getCountrySentToName() + "'" +
            ", citySentToId=" + getCitySentToId() +
            ", citySentToName='" + getCitySentToName() + "'" +
            ", fragile='" + isFragile() + "'" +
            ", needCooler='" + isNeedCooler() + "'" +
            ", otherNote='" + isOtherNote() + "'" +
            ", otherNoteInfo='" + getOtherNoteInfo() + "'" +
            ", itemWeight=" + getItemWeight() +
            ", packageSizeId=" + getPackageSizeId() +
            ", packageSizeName='" + getPackageSizeName() + "'" +
            ", needReceipt='" + isNeedReceipt() + "'" +
            ", priceItem=" + getPriceItem() +
            ", serviceFee=" + getServiceFee() +
            ", jastipFee=" + getJastipFee() +
            ", totalFee=" + getTotalFee() +
            ", acceptedOfferingId=" + getAcceptedOfferingId() +
            ", shoppingDate='" + getShoppingDate() + "'" +
            ", deliveryDate='" + getDeliveryDate() + "'" +
            "}";
    }
}
